### ISSUE TITLE
don't rebase/overwrite git master

### ISSUE THREAD

**Issue by purpleidea** [ffrank/puppet-mgmtgraph#5]
I got a sneaking suspicion this is happening. Except for emergencies where someone hacked your repo or you really made a bad push and you fixed in near instantly, don't change git master once you've pushed something. You can git revert a patch instead.

eg: https://github.com/ffrank/puppet-mgmtgraph/commit/1e0d15ddfc19805318eacec9bc9f144f27687938 hit git master, then disappeared.

Cheers!

**Comment by ffrank** [comment]
Oops. Yes I rebuilt master recently after inadvertently breaking my own build.

Sorry, I'd hoped nobody was tracking so closely 😭

**Comment by purpleidea** [comment]
@ffrank NP. Probably okay to cheat a few times for now. To avoid this problem I use tpush: https://ttboj.wordpress.com/2016/02/16/introducing-git-tpush/
