### ISSUE TITLE
metadata version doesn't match with face's version

### ISSUE THREAD

**Issue by igalic** [ffrank/puppet-mgmtgraph#6]
The current HEAD contains the following [line](https://github.com/ffrank/puppet-mgmtgraph/blob/cbea7667008736cfa4336331a728d1f435133f4c/lib/puppet/face/mgmtgraph.rb#L5)

```ruby
Puppet::Face.define(:mgmtgraph, '0.0.1') do
```

This code doesn't match up with the current version encoded in the [metadata.json](https://github.com/ffrank/puppet-mgmtgraph/blob/cbea7667008736cfa4336331a728d1f435133f4c/metadata.json#L3): `0.3.0`.

**Comment by ffrank** [comment]
🤔 
I'm making changes to the module, but not each of them implies a change to the Face API. I'm pretty sure putting those into lockstep will lead to many tears in the future (but I'm not sure).

**Comment by ffrank** [comment]
(But sure enough, I have made API changes that were not reflected in the Face version which, also, may cause some tears for apt readers of the code history, down the line.)

**Comment by ffrank** [comment]
So, I will try to be more diligent with maintaining SemVer wrt. the Face API version, with the exception that I will sync it to the module version once, when the module reaches 1.0.

Hope that makes sense.
