### ISSUE TITLE
Should missing resources be mentioned in stats command?

### ISSUE THREAD

**Issue by purpleidea** [ffrank/puppet-mgmtgraph#9]
With version 0.4.1 (AFAICT)

I ran:
```
puppet mgmtgraph stats --code 'file { "/tmp/test": ensure => present, seltype => "tmp_t" } -> package { "cowsay": ensure => installed } -> schedule { "puppet": period => hourly, repeat => 2 }'
```
and got the following output:

```
Warning: GettextSetup is not available, skipping GettextSetup initialization for modules.
   (file & line not available)
connect: No such file or directory
Please make sure that the zfs-fuse daemon is running.
internal error: failed to initialize ZFS library
    1x File[...] cannot translate attribute 'seltype', attribute is ignored
```

I would have expected to see something about the `schedule` resource, shouldn't I? (since there isn't an equivalent in mgmt)

Thanks!

**Comment by ffrank** [comment]
I pushed a fix to master. Do you think you can test this without a new Forge release? (If not, that's fine, I'll just release it in that case.)

**Comment by purpleidea** [comment]
@ffrank Sorry for the delay here... Happy to test... What's the best way to do run the install?

**Comment by ffrank** [comment]
Same /o\

Best way is through Forge, so I will just release it (if I don't forget again).
